### ISSUE TITLE
Cannot be installed with Grove

### ISSUE THREAD

**Issue by steerio** [Skinney/murmur3#3]
When trying to install a library through [Grove](https://github.com/panosoft/elm-grove) that depends on Murmur3, the following happens:

```
ERROR: Package Skinney/murmur3 has the following errors:
        npm json version doesn't match elm json version
        npm name: murmur3 must be in the format <user>/<repo>
        npm name: murmur3 must start with an @
        npm name: murmur3 must match elm json repository: Skinney/murmur3
```

This can easily be solved by updating `package.json` according to the above requirements. I would gladly do a PR, but as the change directly involves the version number, it would be impractical.

**Comment by robinheghan** [comment]
It's not really a goal of mine to support an unofficial package manager, especially one which validates something which is only used while testing the library.

Could you run a quick test? Does it work with `elm-dict-extra`?

**Comment by robinheghan** [comment]
Sorry, `elm-community/dict-extra` i mean.

**Comment by steerio** [comment]
The output of installing that project:

```
ERROR: Package elm-community/dict-extra has the following errors:
        version is missing
        name is missing
```
That checks out, as its `package.json` is very minimal.

Regarding supporting Grove, I understand your point of view, and you have every right to have your concerns, but please allow me to describe my situation, which I think is probably not that unique.

In my project I'd like to use a package called `elm-web3`, which has native code in it, so cannot be released in the official package manager. Now, if I install it through Grove, the whole dependency tree has to be installed the same way, and that fails at murmur3. I can't just fork it to rename it to `@steerio/murmur3`, I'd have to fork and modify all projects in the branch of the dependency tree above and including murmur3.

Obviously this state of things is not your fault, neither that of any other package maintainer.

Then again, the rules prescribed by Grove are actually not Grove-specific and kind of sane. Matching versions sounds a-ok to me, and there's also no point in sticking to the `murmur3` project name in `package.json`, as that name is already taken in npm by someone who abandoned their package 5 years ago (and one could also argue that globally thinking, this unprefixed name would be misleading for the Node world anyway).

Should you decide to change it, I'll give you any help I can.

**Comment by robinheghan** [comment]
Sorry, I'm not interested in fixing this. While fixing this thing once isn't really a problem, it's probably going to happen with every release as I personally don't use Groove, and considering it's not an official pm, I'm unlikely to do so in the future.

I also don't think Grove's validation makes sense. This package is not, and is not to be, published on npm, so who cares about the version and name? For that matter, since this project only actually has test dependencies, and no native dependencies, why should the `package.json` matter at all?

I'm considering this a problem with Grove.

**Comment by steerio** [comment]
Basically what it wants to be happy is this:

```
  "name": "@Skinney/murmur3",
  "version": "2.0.5",
```

**Comment by steerio** [comment]
All right, understood.

I'll try to take up the matter with the Grove team, because at the end of the day the status quo means that there's basically no sane way to use packages like `elm-web3`, which means the work their developers are putting in them might have no practical point.

**Comment by steerio** [comment]
Also thank you for taking your time, your input will probably be very valuable in making this argument.

**Comment by robinheghan** [comment]
I don't think should be a hard problem for Grove to handle, at least from my point of view. If Grove can find `exposes-native-modules: true` in `elm-package.json`, then `package.json` might be important and thus should be validated, otherwise it's guaranteed to not need any packages from npm to build and should be ignored.

Since Elm doesn't care about `package.json`, most Elm developers don't either, and only use npm to set up testing. Grove will have problems with many packages in this case.

**Comment by cmditch** [comment]
@Skinney Agreed. Btw, thanks for opening up the issue https://github.com/panosoft/elm-grove/issues/11

@steerio I've done a bit of cleanup. Decoupled the "test suite" from the actual package, and am using elm-github-install for the time being. Check the updated README on elm-web3. Cheers!
