### ISSUE TITLE
Version mismatch due to re-release

### ISSUE THREAD

**Issue by tasuki** [Skinney/murmur3#8]
@robinheghan the consequences of switching from `2.0.8` to `1.0.0` are rather unfortunate. Why would you downgrade a package like this?

Eg https://github.com/ggb/elm-bloom/blob/master/elm.json#L12 depends on `"Skinney/murmur3": "2.0.7 <= v < 3.0.0"`. I think it'd handle the redirect to `robinheghan/murmur3` just fine, but the downgrade from `2.0.8` to `1.0.0`... nope. I don't control `elm-bloom` - how am I supposed to deal with this? I don't think it's fair to say the `elm-bloom` maintainer is responsible - they just used your package, expecting the existing versions not to disappear. Is that too much to ask?

Could you please go back to the original versioning so as to stop breaking everything that depends on your package?

Also, thank you for your package. But I'm actually really mad at you for gratuitously breaking things :wink:

**Comment by robinheghan** [comment]
When publishing a new package to the elm package system (the name of the package has changed) it _has to_ be version 1.0.0.

Even if the version had be correct, this would still fail since the name of the package is different.

I originally did not intend to re-publish packages, as github redirects new username to old username, but since the package _hash_  has changed, elm package manager will not allow old packages to still work.

**Comment by tasuki** [comment]
Thank you for your quick response. So what is the "right" solution here? Open a PR to `elm-bloom` and all the other projects that depend on `murmur3`?

**Comment by robinheghan** [comment]
Yeah, the best would be if `elm-bloom` released a new version with the updated dependency.

If you're in a hurry, you can also deploy your own fork of `elm-bloom` with the fix.

**Comment by tasuki** [comment]
I'm not in a hurry, I'm worried how the Elm ecosystem can thrive if breaking things is this easy. It seems insane that just because you changed your GitHub handle, all the users of your library must break.

Wouldn't releasing this as `2.0.8` fix this?

**Comment by robinheghan** [comment]
The Elm language is young, there are bound to be bugs. The Elm package manager has been designed to allow this, but didn't take into account that hashes change when the username changes. It'll likely be fixed in a future version.

Why would that fix it?

The elm package manager has no record that there exists a Skinney/murmur3 version higher than 2.0.7. Releasing a different package (robinheghan/murmur3) won't change that.

That I've released a 1.0.0 of robinheghan/murmur3 also doesn't matter, as its a different package. It doesnt't affect anyone not using Skinney/murmur3 1.0.0.

**Comment by tasuki** [comment]
I see, probably you're right. Thank you for your patience.

[Edit: I was getting a 404 from GitHub when being redirected to `robinheghan/murmur3` and trying to retrieve the inexistent version. That's why I thought publishing that might help. But I know nothing about Elm packaging.]
